// Code generated by layout. DO NOT EDIT.

package example

import (
	"io"
	"unsafe"
)

func NewPageAligned() *PageAligned {
	p := &PageAligned{}
	// Allocate 4096 + 511 to guarantee 512-byte alignment
	p.backing = make([]byte, 4607)
	
	// Find 512-byte aligned offset
	addr := uintptr(unsafe.Pointer(&p.backing[0]))
	offset := int(((addr + 511) &^ 511) - addr)
	
	// Slice aligned region
	p.buf = p.backing[offset : offset+4096]
	return p
}

func (p *PageAligned) MarshalLayout() ([]byte, error) {
	// Header: uint16 at [0, 2)
	*(*uint16)(unsafe.Pointer(&p.buf[0])) = p.Header

	// Body: []byte at [2, 4088)
	// Body is already sliced from p.buf, no copy needed

	// Footer: uint64 at [4088, 4096)
	*(*uint64)(unsafe.Pointer(&p.buf[4088])) = p.Footer

	return p.buf[:], nil
}

func (p *PageAligned) UnmarshalLayout() error {
	// Header: uint16 at [0, 2)
	p.Header = *(*uint16)(unsafe.Pointer(&p.buf[0]))

	// Body: []byte at [2, 4088)
	p.Body = p.buf[2:4088]

	// Footer: uint64 at [4088, 4096)
	p.Footer = *(*uint64)(unsafe.Pointer(&p.buf[4088]))

	return nil
}

func (p *PageAligned) LoadFrom(r io.Reader) error {
	if _, err := io.ReadFull(r, p.buf[:]); err != nil {
		return err
	}
	return p.UnmarshalLayout()
}

func (p *PageAligned) WriteTo(w io.Writer) error {
	if _, err := p.MarshalLayout(); err != nil {
		return err
	}
	_, err := w.Write(p.buf[:])
	return err
}

