// Code generated by layout. DO NOT EDIT.

package example

import (
	"unsafe"
)

// Clone creates a copy of the PageZeroCopy
func (p *PageZeroCopy) Clone() *PageZeroCopy {
	clone := *p
	return &clone
}

// GetHeader returns uint16 at offset 0
func (p *PageZeroCopy) GetHeader() uint16 {
	return *(*uint16)(unsafe.Pointer(&p.buf[0]))
}

// SetHeader sets uint16 at offset 0
func (p *PageZeroCopy) SetHeader(v uint16) {
	*(*uint16)(unsafe.Pointer(&p.buf[0])) = v
}

// GetFooter returns uint64 at offset 4088
func (p *PageZeroCopy) GetFooter() uint64 {
	return *(*uint64)(unsafe.Pointer(&p.buf[4088]))
}

// SetFooter sets uint64 at offset 4088
func (p *PageZeroCopy) SetFooter(v uint64) {
	*(*uint64)(unsafe.Pointer(&p.buf[4088])) = v
}


